//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDADE()
        {
            this.INSCRIPCIONES = new HashSet<INSCRIPCIONE>();
            this.HABILIDADES = new HashSet<HABILIDADE>();
            this.NECESIDADES = new HashSet<NECESIDADE>();
            this.ODS = new HashSet<OD>();
        }
    
        public short CODACTIVIDAD { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public string ESTADO_APROBACION { get; set; }
        public string ESTADO_NEW { get; set; }
        public string DIRECCION { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public short MAX_PARTICIPANTES { get; set; }
        public string CIF_EMPRESA { get; set; }
        public string SECTOR { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCIONE> INSCRIPCIONES { get; set; }
        public virtual ORGANIZACIONE ORGANIZACIONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABILIDADE> HABILIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NECESIDADE> NECESIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OD> ODS { get; set; }
    }
}
