//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctrine_migration_versions
    {
        public string version { get; set; }
        public Nullable<System.DateTime> executed_at { get; set; }
        public Nullable<int> execution_time { get; set; }
    }
}
