//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPCIONE
    {
        public int id { get; set; }
        public string ESTADO { get; set; }
        public string DNI_VOLUNTARIO { get; set; }
        public Nullable<short> CODACTIVIDAD { get; set; }
    
        public virtual ACTIVIDADE ACTIVIDADE { get; set; }
        public virtual VOLUNTARIO VOLUNTARIO { get; set; }
    }
}
