//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTOINTEREntities : DbContext
    {
        public PROYECTOINTEREntities()
            : base("name=PROYECTOINTEREntities")
        {
        }

        public PROYECTOINTEREntities(string cadenaConexion)
            : base(cadenaConexion)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVIDADE> ACTIVIDADES { get; set; }
        public virtual DbSet<CICLO> CICLOS { get; set; }
        public virtual DbSet<doctrine_migration_versions> doctrine_migration_versions { get; set; }
        public virtual DbSet<HABILIDADE> HABILIDADES { get; set; }
        public virtual DbSet<INSCRIPCIONE> INSCRIPCIONES { get; set; }
        public virtual DbSet<INTERES> INTERESES { get; set; }
        public virtual DbSet<NECESIDADE> NECESIDADES { get; set; }
        public virtual DbSet<OD> ODS { get; set; }
        public virtual DbSet<administrador> administradors { get; set; }
        public virtual DbSet<notificacion> notificacions { get; set; }
        public virtual DbSet<ORGANIZACIONE> ORGANIZACIONES { get; set; }
        public virtual DbSet<VOLUNTARIO> VOLUNTARIOS { get; set; }
    }
}
