//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public bool leido { get; set; }
        public string tipo { get; set; }
        public string voluntario_dni { get; set; }
        public string organizacion_cif { get; set; }
    
        public virtual VOLUNTARIO VOLUNTARIO { get; set; }
        public virtual ORGANIZACIONE ORGANIZACIONE { get; set; }
    }
}
