//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZACIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGANIZACIONE()
        {
            this.ACTIVIDADES = new HashSet<ACTIVIDADE>();
            this.notificacions = new HashSet<notificacion>();
        }
    
        public string CIF { get; set; }
        public string NOMBRE { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string SECTOR { get; set; }
        public string DIRECCION { get; set; }
        public string LOCALIDAD { get; set; }
        public string CP { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTACTO { get; set; }
        public string ESTADO { get; set; }
        public string FCM_TOKEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDADE> ACTIVIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacions { get; set; }
    }
}
