//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLUNTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOLUNTARIO()
        {
            this.INSCRIPCIONES = new HashSet<INSCRIPCIONE>();
            this.notificacions = new HashSet<notificacion>();
            this.HABILIDADES = new HashSet<HABILIDADE>();
            this.INTERESES = new HashSet<INTERES>();
        }
    
        public string DNI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string CORREO { get; set; }
        public string ZONA { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string EXPERIENCIA { get; set; }
        public bool COCHE { get; set; }
        public string DISPONIBILIDAD { get; set; }
        public string IDIOMAS { get; set; }
        public string ESTADO_VOLUNTARIO { get; set; }
        public string FCM_TOKEN { get; set; }
        public Nullable<short> CURSO_CICLOS { get; set; }
        public string NOMBRE_CICLOS { get; set; }
    
        public virtual CICLO CICLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCIONE> INSCRIPCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABILIDADE> HABILIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERES> INTERESES { get; set; }
    }
}
