/* SCRIPT CORREGIDO PARA MICROSOFT SQL SERVER 2022 */

-- 1. Crear la base de datos
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'PROYECTOINTER')
BEGIN
    CREATE DATABASE [PROYECTOINTER];
END
GO

USE [PROYECTOINTER];
GO

-- ==========================================================
-- ELIMINACIÓN DE TABLAS (En orden para evitar conflictos de FK)
-- ==========================================================
IF OBJECT_ID('[VOLUNTARIOS_INTERESES]', 'U') IS NOT NULL DROP TABLE [VOLUNTARIOS_INTERESES];
IF OBJECT_ID('[VOLUNTARIOS_HABILIDADES]', 'U') IS NOT NULL DROP TABLE [VOLUNTARIOS_HABILIDADES];
IF OBJECT_ID('[ACTIVIDADES_ODS]', 'U') IS NOT NULL DROP TABLE [ACTIVIDADES_ODS];
IF OBJECT_ID('[ACTIVIDADES_NECESIDADES]', 'U') IS NOT NULL DROP TABLE [ACTIVIDADES_NECESIDADES];
IF OBJECT_ID('[ACTIVIDADES_HABILIDADES]', 'U') IS NOT NULL DROP TABLE [ACTIVIDADES_HABILIDADES];
IF OBJECT_ID('[INSCRIPCIONES]', 'U') IS NOT NULL DROP TABLE [INSCRIPCIONES];
IF OBJECT_ID('[notificacion]', 'U') IS NOT NULL DROP TABLE [notificacion];
IF OBJECT_ID('[ACTIVIDADES]', 'U') IS NOT NULL DROP TABLE [ACTIVIDADES];
IF OBJECT_ID('[VOLUNTARIOS]', 'U') IS NOT NULL DROP TABLE [VOLUNTARIOS];
IF OBJECT_ID('[ORGANIZACIONES]', 'U') IS NOT NULL DROP TABLE [ORGANIZACIONES];
IF OBJECT_ID('[CICLOS]', 'U') IS NOT NULL DROP TABLE [CICLOS];
IF OBJECT_ID('[HABILIDADES]', 'U') IS NOT NULL DROP TABLE [HABILIDADES];
IF OBJECT_ID('[INTERESES]', 'U') IS NOT NULL DROP TABLE [INTERESES];
IF OBJECT_ID('[NECESIDADES]', 'U') IS NOT NULL DROP TABLE [NECESIDADES];
IF OBJECT_ID('[ODS]', 'U') IS NOT NULL DROP TABLE [ODS];
IF OBJECT_ID('[administrador]', 'U') IS NOT NULL DROP TABLE [administrador];
IF OBJECT_ID('[doctrine_migration_versions]', 'U') IS NOT NULL DROP TABLE [doctrine_migration_versions];
GO

-- ==========================================================
-- CREACIÓN DE TABLAS MAESTRAS
-- ==========================================================

CREATE TABLE [CICLOS] (
    [CURSO] SMALLINT,
    [NOMBRE] NVARCHAR(100),
    PRIMARY KEY ([CURSO], [NOMBRE])
);

CREATE TABLE [ORGANIZACIONES] (
    [CIF] NCHAR(9) PRIMARY KEY,
    [NOMBRE] NVARCHAR(40),
    [EMAIL] VARCHAR(100) UNIQUE,
    [SECTOR] NVARCHAR(100),
    [DIRECCION] NVARCHAR(40),
    [LOCALIDAD] NVARCHAR(40),
    [CP] CHAR(5),
    [DESCRIPCION] NVARCHAR(200),
    [CONTACTO] NVARCHAR(40),
    [ESTADO] NVARCHAR(20),
    [FCM_TOKEN] NVARCHAR(255)
);

CREATE TABLE [HABILIDADES] (
    [id] INT PRIMARY KEY,
    [nombre] NVARCHAR(100)
);

CREATE TABLE [INTERESES] (
    [id] INT PRIMARY KEY,
    [nombre] NVARCHAR(100)
);

CREATE TABLE [NECESIDADES] (
    [id] INT PRIMARY KEY,
    [nombre] NVARCHAR(100)
);

CREATE TABLE [ODS] (
    [id] INT PRIMARY KEY,
    [nombre] NVARCHAR(100),
    [descripcion] NVARCHAR(255),
    [color] NVARCHAR(7)
);

-- ==========================================================
-- CREACIÓN DE TABLAS CON CLAVES FORÁNEAS
-- ==========================================================

CREATE TABLE [ACTIVIDADES] (
    [CODACTIVIDAD] SMALLINT PRIMARY KEY,
    [NOMBRE] NVARCHAR(40),
    [ESTADO] NVARCHAR(255),
    [ESTADO_APROBACION] NVARCHAR(20) DEFAULT N'PENDIENTE',
    [ESTADO_NEW] NVARCHAR(255),
    [DIRECCION] NVARCHAR(40),
    [SECTOR] NVARCHAR(50),
    [DESCRIPCION] VARCHAR(MAX),
    [FECHA_INICIO] DATETIME2(6),
    [FECHA_FIN] DATETIME2(6),
    [MAX_PARTICIPANTES] SMALLINT,
    [CIF_EMPRESA] NCHAR(9),
    CONSTRAINT [FK_ACTIVIDADES_ORG] FOREIGN KEY ([CIF_EMPRESA]) REFERENCES [ORGANIZACIONES] ([CIF])
);

CREATE TABLE [VOLUNTARIOS] (
    [DNI] NCHAR(9) PRIMARY KEY,
    [NOMBRE] NVARCHAR(100),
    [APELLIDO1] NVARCHAR(100),
    [APELLIDO2] NVARCHAR(100),
    [CORREO] NVARCHAR(40),
    [ZONA] NVARCHAR(100),
    [FECHA_NACIMIENTO] DATETIME2(6),
    [EXPERIENCIA] NVARCHAR(200),
    [COCHE] BIT,
    [DISPONIBILIDAD] VARCHAR(MAX),
    [IDIOMAS] VARCHAR(MAX),
    [ESTADO_VOLUNTARIO] NVARCHAR(20),
    [FCM_TOKEN] NVARCHAR(255),
    [CURSO_CICLOS] SMALLINT,
    [NOMBRE_CICLOS] NVARCHAR(100),
    CONSTRAINT [FK_VOLUNTARIOS_CICLOS] FOREIGN KEY ([CURSO_CICLOS], [NOMBRE_CICLOS]) REFERENCES [CICLOS] ([CURSO], [NOMBRE])
);

CREATE TABLE [INSCRIPCIONES] (
    [id] INT PRIMARY KEY,
    [ESTADO] NVARCHAR(20),
    [DNI_VOLUNTARIO] NCHAR(9),
    [CODACTIVIDAD] SMALLINT,
    CONSTRAINT [FK_INSCRIPCIONES_ACT] FOREIGN KEY ([CODACTIVIDAD]) REFERENCES [ACTIVIDADES] ([CODACTIVIDAD]),
    CONSTRAINT [FK_INSCRIPCIONES_VOL] FOREIGN KEY ([DNI_VOLUNTARIO]) REFERENCES [VOLUNTARIOS] ([DNI])
);

-- Tablas intermedias N:M
CREATE TABLE [ACTIVIDADES_HABILIDADES] (
    [CODACTIVIDAD] SMALLINT,
    [HABILIDAD_ID] INT,
    PRIMARY KEY ([CODACTIVIDAD], [HABILIDAD_ID]),
    FOREIGN KEY ([CODACTIVIDAD]) REFERENCES [ACTIVIDADES]([CODACTIVIDAD]),
    FOREIGN KEY ([HABILIDAD_ID]) REFERENCES [HABILIDADES]([id])
);

CREATE TABLE [ACTIVIDADES_ODS] (
    [CODACTIVIDAD] SMALLINT,
    [ODS_ID] INT,
    PRIMARY KEY ([CODACTIVIDAD], [ODS_ID]),
    FOREIGN KEY ([CODACTIVIDAD]) REFERENCES [ACTIVIDADES]([CODACTIVIDAD]),
    FOREIGN KEY ([ODS_ID]) REFERENCES [ODS]([id])
);

CREATE TABLE [VOLUNTARIOS_HABILIDADES] (
    [DNI] NCHAR(9),
    [HABILIDAD_ID] INT,
    PRIMARY KEY ([DNI], [HABILIDAD_ID]),
    FOREIGN KEY ([DNI]) REFERENCES [VOLUNTARIOS]([DNI]),
    FOREIGN KEY ([HABILIDAD_ID]) REFERENCES [HABILIDADES]([id])
);

CREATE TABLE [VOLUNTARIOS_INTERESES] (
    [DNI] NCHAR(9),
    [INTERES_ID] INT,
    PRIMARY KEY ([DNI], [INTERES_ID]),
    FOREIGN KEY ([DNI]) REFERENCES [VOLUNTARIOS]([DNI]),
    FOREIGN KEY ([INTERES_ID]) REFERENCES [INTERESES]([id])
);
GO

-- ==========================================================
-- INSERCIÓN DE DATOS
-- ==========================================================

INSERT INTO [CICLOS] ([CURSO], [NOMBRE]) VALUES 
(2, N'Administración'), (2, N'ASIR'), (2, N'DAM'), (2, N'DAW'), (2, N'Marketing');

INSERT INTO [ORGANIZACIONES] ([CIF], [NOMBRE], [EMAIL], [SECTOR], [DIRECCION], [LOCALIDAD], [CP], [DESCRIPCION], [CONTACTO], [ESTADO]) VALUES
(N'B00000000', N'EcoVida', N'ecovida0@test.com', N'Medio Ambiente', N'Calle 0', N'Pamplona', N'31000', N'Social', N'600', N'aprobado'),
(N'B00000001', N'AyudaDirecta', N'ayuda@test.com', N'Social', N'Calle 1', N'Pamplona', N'31000', N'Social', N'601', N'aprobado');

INSERT INTO [ACTIVIDADES] ([CODACTIVIDAD], [NOMBRE], [ESTADO], [ESTADO_APROBACION], [DIRECCION], [SECTOR], [FECHA_INICIO], [FECHA_FIN], [MAX_PARTICIPANTES], [CIF_EMPRESA]) VALUES
(1, N'Actividad Social 0', N'ABIERTA', N'ACEPTADO', N'Centro 0', N'Animales', '2026-03-10 14:00', '2026-03-10 18:00', 10, N'B00000000'),
(2, N'Actividad Social 1', N'ABIERTA', N'ACEPTADO', N'Centro 1', N'Social', '2026-03-10 14:00', '2026-03-10 18:00', 10, N'B00000001');

INSERT INTO [VOLUNTARIOS] ([DNI], [NOMBRE], [APELLIDO1], [CORREO], [COCHE], [ESTADO_VOLUNTARIO], [CURSO_CICLOS], [NOMBRE_CICLOS]) VALUES
(N'00000000V', N'Carlos', N'Lopez', N'carlos@test.com', 1, N'ACEPTADO', 2, N'DAM'),
(N'12345678T', N'Voluntario', N'Test', N'test@test.com', 1, N'LIBRE', 2, N'DAM');

INSERT INTO [ODS] ([id], [nombre], [color]) VALUES 
(1, N'Pobreza', N'#E5243B'), (3, N'Salud', N'#4C9F38'), (4, N'Educación', N'#C5192D');

INSERT INTO [ACTIVIDADES_ODS] ([CODACTIVIDAD], [ODS_ID]) VALUES (1, 4), (2, 3);
GO